//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduMartFYP1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int adminid { get; set; }
        public string adminusername { get; set; }
        public string adminpassword { get; set; }
    }
}
