//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduMartFYP1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public int ApplicationID { get; set; }
        public int StudenttID { get; set; }
        public int CollegeID { get; set; }
        public int DeciplineID { get; set; }
        public int QuotaID { get; set; }
        public decimal TotalMarks { get; set; }
        public decimal ObtainedMarks { get; set; }
        public decimal Percentage { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual College College { get; set; }
        public virtual Decipline Decipline { get; set; }
        public virtual Quota Quota { get; set; }
        public virtual Student Student { get; set; }
    }
}
