//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduMartFYP1
{
    using System;
    using System.Collections.Generic;
    
    public partial class College
    {
        public College()
        {
            this.Application = new HashSet<Application>();
        }
    
        public int CollegeID { get; set; }
        public string CollegeName { get; set; }
        public string CollegeAddress { get; set; }
        public decimal CollegeContact { get; set; }
        public string CollegeEmail { get; set; }
        public string CollegePassword { get; set; }
        public string Role { get; set; }
    
        public virtual ICollection<Application> Application { get; set; }
    }
}
