//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduMartFYP1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Decipline
    {
        public Decipline()
        {
            this.Application = new HashSet<Application>();
        }
    
        public int DeciplineID { get; set; }
        public string DeciplineName { get; set; }
    
        public virtual ICollection<Application> Application { get; set; }
    }
}
