//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduMartFYP1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EduMartEntities : DbContext
    {
        public EduMartEntities()
            : base("name=EduMartEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Application> Application { get; set; }
        public virtual DbSet<Board> Board { get; set; }
        public virtual DbSet<College> College { get; set; }
        public virtual DbSet<Decipline> Decipline { get; set; }
        public virtual DbSet<Quota> Quota { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<Admin> Admin { get; set; }

        public System.Data.Entity.DbSet<EduMartFYP1.Models.Adminmembership> Adminmemberships { get; set; }
    }
}
